# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '6001685e-2c0d-4d57-b07f-e198dfce3799'

  # Web app name
  webAppName: 'App-nextjs-boilerplate'

  # Environment name
  environmentName: 'App-nextjs-boilerplate'

  # Is running on main branch
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

  sourceSlot: 'staging'
  resourceGroup: 'nextjs-boilerplate'

stages:
- stage: stageBuild
  displayName: Build
  jobs:
  - job: Build
    displayName: Build

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - script: npm ci
      displayName: 'Install & Build'

    - script: |
        npx print-env AGENT
        npx print-env BUILD
        npx print-env SYSTEM
      displayName: Pipeline Environment

    - script: npm run lint
      displayName: 'Lint'

    - script: npm run test:cover
      displayName: 'Tests'

    - task: PublishTestResults@2
      displayName: 'Unit Test - Publish'
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: 'coverage/jest-junit/junit.xml'

    - task: PublishCodeCoverageResults@1
      displayName: 'Code Coverage - Publish'
      condition: succeededOrFailed()
      inputs:
        failIfCoverageEmpty: true
        codeCoverageTool: Cobertura
        summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml

    - task: PublishHtmlReport@1
      displayName: 'HTML Report - Publish'
      condition: succeededOrFailed()
      inputs:
        reportDir: 'coverage/html-report.html'

    - task: ArchiveFiles@2
      displayName: 'Artifact - Archive'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: Artifact - Publish

- stage: stageDeployDev
  displayName: Dev
  dependsOn: stageBuild
  jobs:
    - job: jobDeploy
      displayName: Deploy Dev
      steps:
        - script: 'echo deploy dev'
          displayName: 'Deploy'

    - job: jobDeployValidation
      displayName: E2E Tests - Dev
      dependsOn: jobDeploy
      steps:
        - script: 'echo e2e test'
          displayName: 'Cypress'

- stage: stageDeployQA
  displayName: QA
  dependsOn: stageDeployDev
  jobs:
    - job: jobDeploy
      displayName: Deploy QA
      steps:
        - script: 'echo deploy QA'
          displayName: 'Deploy'

    - job: jobDeployValidation
      displayName: E2E Tests - QA
      dependsOn: jobDeploy
      steps:
        - script: 'echo e2e test'
          displayName: 'Cypress'

    - job: jobApproval
      displayName: Manual Approval
      dependsOn: jobDeployValidation
      pool: server
      steps:
        - task: ManualValidation@0
          timeoutInMinutes: 1
          inputs:
            instructions: |
              ✅ Acceptance criteria is met
              ✅ Regressions pass
            onTimeout: 'reject'

- stage: stageDeployStaging
  displayName: Staging Prod
  dependsOn: stageDeployQA
  jobs:
    - job: jobDeploy
      displayName: Deploy Staging

      steps:
        - script: 'echo deploy Staging'
          displayName: 'Deploy'

    - job: jobDeployValidation
      displayName: E2E Tests Staging
      dependsOn: jobDeploy
      steps:
        - script: 'echo e2e test'
          displayName: 'Cypress'

    - job: jobApproval
      displayName: Manual Approval
      dependsOn: jobDeployValidation
      pool: server
      steps:
        - task: ManualValidation@0
          timeoutInMinutes: 1
          inputs:
            instructions: |
              ✅ Acceptance criteria is met
              ✅ Regressions pass
            onTimeout: 'reject'

- stage: stageDeployProd
  displayName: Prod
  dependsOn: stageDeployStaging
  jobs:
    - job: jobDeploy
      displayName: Deploy Prod
      steps:
        - script: 'echo deploy Prod'
          displayName: 'Deploy'

    - job: jobDeployValidation
      displayName: E2E Tests Prod
      dependsOn: jobDeploy
      steps:
        - script: 'echo e2e test'
          displayName: 'Cypress'

    - job: jobApproval
      displayName: Manual Approval
      dependsOn: jobDeployValidation
      pool: server
      steps:
        - task: ManualValidation@0
          timeoutInMinutes: 1
          inputs:
            instructions: |
              ✅ Acceptance criteria is met
              ✅ Regressions pass
            onTimeout: 'reject'
