jobs:
  - job: jobTemplate
    displayName: template
    dependsOn: jobDeploy
    variables:
      deployedAppUrl: $[ dependencies.jobDeploy.outputs['setVariable.deployedAppUrl'] ]
    steps:
      - script: env | sort
        displayName: Pipeline Environment

      - bash: echo "the variable value is $(deployedAppUrl)"
