jobs:
  - job: jobTemplate
    displayName: Demo Template
    dependsOn: jobDeploy
    variables:
      deployedAppUrl: $[ dependencies.jobDeploy.outputs['setVariable.deployedAppUrl'] ]
      deployedAppUrlEnv: $[ dependencies.jobDeploy.outputs['setVariable.deployedAppUrlEnv'] ]
    steps:
      - script: env | sort
        displayName: Pipeline Environment

      - bash: |
          echo "deployedAppUrl is $(deployedAppUrl)"
          echo "deployedAppUrlEnv is $(deployedAppUrlEnv)"
