trigger:
  branches:
    include:
      - '*'

stages:
  - stage: deploy
    displayName: Production
    jobs:
      - deployment: jobDeployEnv
        displayName: Deploy - Env
        environment: Dev
        pool:
          vmImage: $ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - bash: |
                    echo "##vso[task.setvariable variable=deployedAppUrlEnv;isOutput=true;]someValueEnv"
                    echo "deployedAppUrlEnv is $(deployedAppUrlEnv)"
                  name: setVariable

                - script: env | sort
                  displayName: Pipeline Environment

      - job: jobDeploy
        displayName: Deploy
        steps:
          - bash: |
              echo "##vso[task.setvariable variable=deployedAppUrl;isOutput=true;]someValue"
              echo "variable value is $(deployedAppUrl)"
            name: setVariable

          - script: env | sort
            displayName: Pipeline Environment

      - job: jobDemo
        displayName: Demo
        dependsOn: jobDeploy
        variables:
          deployedAppUrl: $[ dependencies.jobDeploy.outputs['setVariable.deployedAppUrl'] ]
          deployedAppUrlEnv: $[ dependencies.jobDeploy.outputs['setVariable.deployedAppUrlEnv'] ]
        steps:
          - script: env | sort
            displayName: Pipeline Environment

          - bash: |
              echo "deployedAppUrl is $(deployedAppUrl)"
              echo "deployedAppUrlEnv is $(deployedAppUrlEnv)"

      - template: pipeline-sandbox-template.yml
