trigger: none
pr:
- main

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: skipE2eTests
    type: boolean
    default: true   # set to false for e2e tests to run

variables:
  - template: templates/variables.yml
    parameters:
      skipE2eTests: ${{ parameters.skipE2eTests }}

jobs:
  - template: templates/build.yml
